# use this file to create a conda environment
# conda env create -file environment.yml --name myenv
name: cvxpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scipy
  - numpy
  - matplotlib
  - cvxpy
  - cvxopt
  - pip